name: Build Spotube Plugin

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.0

      - name: Install Hetu Script Dev Tools
        run: dart pub global activate hetu_script_dev_tools

      - name: Compile the Plugin
        run: |
          export PATH="$HOME/.pub-cache/bin:$PATH"
          make build
          

      - name: Upload .smplug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-music-plugin
          # This tells GitHub to search every single folder for the file
          path: |
            **/*.smplug
            **/*.bytes

          
